### ISSUE TITLE
License key not delivered

### ISSUE THREAD

**Issue by cami3** [Some1private/ElijahPrintifyAutomation#1]
Hello, I was informed that my license key would be delivered to my email within 30 minutes, but I haven't received it yet. I also contacted via Telegram, but I haven't received a response yet. Please assist me with this issue. Thank you

**Comment by Some1private** [comment]
I spoke to you on telegram and the license key was delivered to you. Sorry for the inconvenience.

**Comment by cami3** [comment]
Thank you for resolving the issue and providing the license key. The app is great, and I appreciate your support.
